### PR TITLE
Update appendix-generator.py

### PR DESCRIPTION
**Pull request by sopho-s**
I've made it better

### CODE REVIEW

**Comment by Choc-a-Block** [comment]
Dear @sopho-s,

Thank you for your contribution to the project. However, upon reviewing your pull request, it has come to my attention that there are elements of inappropriate code included.

Please note that my project maintains a strict policy against such content, as it does not align with my values of inclusivity and professionalism. I kindly ask you to revise your code and ensure that all contributions adhere to guidelines.

I appreciate your understanding and cooperation in this matter.

Best regards,
@Choc-a-Block

**Comment by sopho-s** [comment]
):

**Comment by sopho-s** [comment]
@Choc-a-Block I'm very sad now

**Comment by Choc-a-Block** [comment]
Dear @sopho-s ,

Thank you for your response and your understanding of the project's policies. I appreciate your dedication to improving the codebase.

I understand your frustration, and I apologize for any inconvenience caused. However, it's important to maintain a high standard of quality and professionalism in the codebase, which includes adhering to the guidelines regarding appropriate content.

I encourage you to revise the code in accordance with the policies, and I remain open to reviewing your contributions once they align with our standards.

Thank you for your cooperation and continued support of the project.

Best regards,
@Choc-a-Block

**Pull request closed without merging**
